PENAI_API_KEY="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"
LANGCHAIN_TRACING_V2=true
LANGCHAIN_ENDPOINT="https://api.smith.langchain.com"
LANGCHAIN_API_KEY="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"
LANGCHAIN_PROJECT="pr-political-pathway-1"